# NOTE: Generated By HttpRunner v4.3.0
# FROM: testcases/login/get_userinfo.yml
from httprunner import HttpRunner, Config, Step, RunRequest
from httprunner import RunTestCase

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent.parent))

from testcases.login.himo_login_test import TestCaseHimoLogin as HimoLogin


class TestCaseGetUserinfo(HttpRunner):

    config = Config("获取用户信息").base_url("${ENV(php_base_url)}").verify(False)

    teststeps = [
        Step(RunTestCase("获取登录鉴权").call(HimoLogin).export(*["stream_id"])),
        Step(
            RunRequest("获取用户信息")
            .get("/appointment_platform/user/user/detail")
            .with_headers(**{"X-Stream-Id": "$stream_id"})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.success", True)
        ),
    ]


if __name__ == "__main__":
    TestCaseGetUserinfo().test_start()
