# NOTE: Generated By HttpRunner v4.3.0
# FROM: testcases/login/himo_login.yml
from httprunner import HttpRunner, Config, Step, RunRequest


class TestCaseHimoLogin(HttpRunner):

    config = Config("预约端登录").base_url("${ENV(php_base_url)}").verify(False)

    teststeps = [
        Step(
            RunRequest("账号密码登录")
            .with_variables(
                **{"phone": "${ENV(USERNAME)}", "password": "${ENV(password)}"}
            )
            .get("/user_auth/login/pass")
            .with_params(**{"phone": "$phone", "pass": "$password", "brand": "himo"})
            .extract()
            .with_jmespath('headers."X-Stream-Id"', "stream_id")
            .with_jmespath('headers."Content-Type"', "Content-Type")
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.success", True)
            .assert_equal("body.msg", "login success")
        ),
    ]


if __name__ == "__main__":
    TestCaseHimoLogin().test_start()
