# NOTE: Generated By HttpRunner v4.3.0
# FROM: testcases/login/login.yml
from httprunner import HttpRunner, Config, Step, RunRequest


class TestCaseLogin(HttpRunner):

    config = Config("中台登录").base_url("${ENV(java_base_url)}").verify(False)

    teststeps = [
        Step(
            RunRequest("账号密码登录")
            .with_variables(
                **{
                    "phone": "${ENV(USERNAME)}",
                    "password": "${ENV(PASSWORD)}",
                    "grant_type": "passwd",
                    "dingLoginVersion": "new",
                }
            )
            .post("/pbc-auth/oauth/token")
            .with_params(
                **{
                    "grant_type": "$grant_type",
                    "phone": "$phone",
                    "password": "$password",
                    "dingLoginVersion": "$dingLoginVersion",
                }
            )
            .with_headers(
                **{
                    "authorization": "Basic NW5LZ2NxRFY6Y2ZjMTI5NjQ3ZWMwMjk0Zjc5MDQyNWE1OTY2Yjc0MmVjMGZhNTcwOQ=="
                }
            )
            .extract()
            .with_jmespath("body.msg.access_token", "access_token")
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.success", True)
            .assert_equal("body.error_code", None)
        ),
    ]


if __name__ == "__main__":
    TestCaseLogin().test_start()
