# NOTE: Generated By HttpRunner v4.3.0
# FROM: testcases/company_manage/add_company.yml
from httprunner import HttpRunner, Config, Step, RunRequest
from httprunner import RunTestCase

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent.parent))

from testcases.company_manage.mall_company_test import (
    TestCaseMallCompany as MallCompany,
)


class TestCaseAddCompany(HttpRunner):

    config = (
        Config("公司管理")
        .variables(**{"company_name": "${gender_name()}"})
        .base_url("${ENV(java_base_url)}")
        .verify(False)
    )

    teststeps = [
        Step(
            RunTestCase("获取集团iD、公司类型")
            .call(MallCompany)
            .export(
                *[
                    "access_token",
                    "group_company_id",
                    "default_company_type",
                    "main_company_type",
                    "sub_company_type",
                    "branch_company_type",
                ]
            )
        ),
        Step(
            RunRequest("创建公司")
            .post("/pbc-system/company/add")
            .with_headers(
                **{
                    "Authorization": "Bearer $access_token",
                    "content-type": "application/json;charset=UTF-8",
                }
            )
            .with_json(
                {
                    "address": "${ENV(ADDRESS)}",
                    "groupCompanyId": "$group_company_id",
                    "name": "$company_name",
                    "type": "$default_company_type",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.msg", "添加成功")
            .assert_equal("body.success", True)
        ),
    ]


if __name__ == "__main__":
    TestCaseAddCompany().test_start()
